language: node_js
node_js:
  - "10"
  - "8"
notifications:
  recipients:
    - piro.outsider.reflex@gmail.com
before_script:
  - npm install
  - make update_extlib
  - make install_extlib
script:
  - make lint
before_deploy:
  - make
deploy:
  provider: releases
  api_key:
    secure: "wIowtcfYIJ6wJYVZ9LHXL7T/w2RPKhax7eHY7Vr3QnblteB4scfCBAwNY8/3hOtBKNDRjGf+hD71DF4s0dh09JNHcprtP/SV4TRHbSImljI9YUM/gLX3BjaR3kp4xxxy+E7cXcNByIgdQDjft/cHbbyGis9bEcNrMNc1/oUdCWLoK8+iyXV12B3QQtD6VQ/wE4aW90vP1XUg1LFrm2N6ojvMKw2hDYISPgk9cjZ/LW+8ECcWByOnsxC8JEAjsuL8E9zRFtojrRXvJMh8dTxukUE3xf72FQdlAX5oeHPf5LPX/f4QGLIzUgB7uJbPyOyjpdmHYwU9P+DELGcRMw7/UanSaQKc+MIVwYL6ZyTZrqXxtJNqcZNb6LedRdx2/I4NZsh93NGysSAZ0xdsO3W+sHgjuwwgt/+eFu7YFMAnHbKHWKBASi7/7qlNm2q1kjmYXyAXC7e8BeElBwf3SU6XGkhhqP49HmXkYiW+PipVHgtvtgRd/aYGg9XuQDnebfA5Te2DfrqV6ZbHcSOsaQTTN2b46qKFSxqVKsz7db7EdHRI3ix1znC5q5ipZk2NePZvKk9qXNeDRYH0K/i41F0oRldHkErvzia97qZv3bEf9CwFY1ADM9zdIUGgkdjJtSjUEUfvXaCtNRvpEzW+DrfWm0IITNJt/G96AUrXfWpKA4I="
  file:
    - save-selected-tabs-to-files.xpi
  skip_cleanup: true
  on:
    repo: piroor/save-selected-tabs-to-files
    tags: true
